import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("flagma.server.kotlin-application-conventions")
}

dependencies {
    implementation(armeriaLib.armeria)
    implementation(armeriaLib.armeria.kotlin)
    implementation(armeriaLib.kotlin.coroutines.core)

    implementation("net.logstash.logback:logstash-logback-encoder:7.4")
    runtimeOnly(armeriaLib.logback14)

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.2")

    implementation("com.linecorp.centraldogma:centraldogma-client-armeria:0.61.3")

    implementation("io.insert-koin:koin-core:3.4.2")
    implementation("io.insert-koin:koin-logger-slf4j:3.4.1")

    testImplementation("io.insert-koin:koin-test:3.4.1")

}

tasks.named<KotlinCompilationTask<*>>("compileKotlin").configure {
    compilerOptions {
        freeCompilerArgs.add("-java-parameters")
    }
}

application {
    // Define the main class for the application.
    mainClass.set("flagma.server.app.AppKt")
}
