version: "3.9"
services:
  centraldogma:
    image: line/centraldogma:latest
    ports:
      - "36462:36462"

  flagma-server:
    depends_on:
      - centraldogma
    links:
      - "centraldogma"
    build:
      context: ./flagma-server
    ports:
      - "9000:9000"
    environment:
      - DOGMA_HOST=centraldogma
    profiles:
      - server
  
  # Observability
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./observability/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./observability/prometheus:/prometheus"
  
  grafana:
    image: grafana/grafana:latest
    links:
      - "prometheus"
    ports:
      - "3000:3000"
    volumes:
      - "./observability/grafana:/var/lib/grafana"

